### PR TITLE
It should work. There was no time to test 

### PR DESCRIPTION
**Pull request by Greatrandom**

### CODE REVIEW

**Comment by rhc54** [comment]
@Greatrandom I have three comments on this request:
1. opal_hwloc_bus_gpu_pci_ids should be named opal_hwloc_base_gpu_pci_ids per our naming conventions
2. please remove the empty comment in rmaps_ppr.c
3. Please give us a better commit message than "FirstCommit" - we'd like to see something that describes what the commit is intended to do.

Thanks!
Ralph

**Comment by artpol84** [comment]
Thank you, Ralph!
That's a non-working commit that Alex want's to discuss with me.
P.S. Am I right that you just monitor my ompi fork? I mean that this commit is by no means should be PR'ed to the main trunk of OMPI. So if this is the case we need to close it :).
Once it will be working solution we will provide good 1 commit with proper description.

**Comment by rhc54** [comment]
I guess I somehow got this on my "watch" list, though I honestly can't recall doing it deliberately. I can "unwatch" it if you prefer, or comment on things like this if you like.

Didn't mean to be looking over your shoulder :-)

**Comment by artpol84** [comment]
No problem at all! I appreciate that you reviewed the commit. Just wanted
to make sure that we are not trying to push the raw code into the trunk.

2015-05-07 17:58 GMT+03:00 rhc54 notifications@github.com:

> I guess I somehow got this on my "watch" list, though I honestly can't
> recall doing it deliberately. I can "unwatch" it if you prefer, or comment
> on things like this if you like.
> 
> Didn't mean to be looking over your shoulder :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/artpol84/ompi/pull/1#issuecomment-99898865.

## 

С Уважением, Поляков Артем Юрьевич
Best regards, Artem Y. Polyakov

**Comment by Greatrandom** [comment]
Added minor fix and rename function.
Don't know why this 2 commits goes into first.

**Pull request merged**
